### populate database
POST {{url}}/populate

### register a user
POST {{url}}/auth/register

{
    "username": "user1",
    "password": "pass12345"
}

### login
POST {{url}}/auth/login

{
    "username": "user1",
    "password": "pass12345"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

### test user token
GET {{url}}/protected/user_demo
AUTHORIZATION: Bearer {{jwt_token}}

### test admin token
GET {{url}}/protected/admin_demo
AUTHORIZATION: Bearer {{jwt_token}}

### Add admin role to user (Login again when role added)
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}


### create a timelog -- User Token
POST {{url}}/timelogs
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "users": ["user1"],
  "dateTime": "2025-12-12T10:00:00",
  "hours": 2.5,
  "description": "Worked on Employee Manager"
}
### find timelog by id -- User Token
GET {{url}}/timelogs/1
Accept: application/json
Authorization: Bearer {{jwt_token}}

### find all existing timelogs -- User Token
GET {{url}}/timelogs
Accept: application/json
Authorization: Bearer {{jwt_token}}

### update a timelog -- User Token
PUT {{url}}/timelogs/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "users": ["user1"],
  "dateTime": "2025-12-12T10:00:00",
  "hours": 3.5,
  "description": "Worked on Employee Manager"
}

### delete timelog -- User Token
DELETE {{url}}/timelogs/1
Accept: application/json
Authorization: Bearer {{jwt_token}}



