### populate database
POST {{url}}/populate

### login
POST {{url}}/auth/login

{
    "username": "admin",
    "password": "1234"
}
> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

### register a user
POST {{url}}/admin/employee/register
AUTHORIZATION: Bearer {{jwt_token}}

{
    "username": "user3",
    "firstName": "John",
    "lastName": "doe",
    "email": "john@com",
    "password": "1234"
}

### Find a user
GET {{url}}/admin/employee/user1
AUTHORIZATION: Bearer {{jwt_token}}

### Find all users
GET {{url}}/admin/employees
AUTHORIZATION: Bearer {{jwt_token}}


### update a user -- Admin Token
PUT {{url}}/admin/employee/user1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "firstName": "Bob",
  "lastName": "doe",
  "email": "bob@com",
  "password": "pass12345"
}

### delete user -- Admin Token
DELETE {{url}}/admin/employee/user1
Accept: application/json
Authorization: Bearer {{jwt_token}}

### login
POST {{url}}/auth/login

{
    "username": "user2",
    "password": "1234"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

### test user token
GET {{url}}/protected/user_demo
AUTHORIZATION: Bearer {{jwt_token}}

### test admin token
GET {{url}}/protected/admin_demo
AUTHORIZATION: Bearer {{jwt_token}}

### create a timelog -- User Token
POST {{url}}/timelogs
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "users": ["user3"],
  "dateTime": "2025-12-12T10:00:00",
  "hours": 2.5,
  "description": "Worked on Employee Manager"
}
### find timelog by id -- User Token
GET {{url}}/timelogs/1
Accept: application/json
Authorization: Bearer {{jwt_token}}

### find all existing timelogs -- Admin Token
GET {{url}}/timelogs
Accept: application/json
Authorization: Bearer {{jwt_token}}

### find for user -- User token
GET {{url}}/timelogs/employee/user2
Accept: application/json
Authorization: Bearer {{jwt_token}}

### update a timelog -- User Token
PUT {{url}}/timelogs/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "users": ["user1"],
  "dateTime": "2025-12-12T10:00:00",
  "hours": 3.5,
  "description": "Worked on Employee Manager"
}

### delete timelog -- User Token
DELETE {{url}}/timelogs/1
Accept: application/json
Authorization: Bearer {{jwt_token}}



